config/routes.rb
Rails.application.routes.draw do

  devise_for :administrators, skip: [:sessions, :passwords, :confirmations, :registrations]
  as :administrator do

    scope '/gdpp-admin' do

      get     '/login'  => 'devise/sessions#new',     as: 'new_administrator_session'
      post    '/login'  => 'devise/sessions#create',  as: 'administrator_session'
      delete  '/logout' => 'devise/sessions#destroy', as: 'destroy_administrator_session'

      get   '/join' => 'devise/registrations#new',    as: 'new_administrator_registration'
      post  '/join' => 'devise/registrations#create', as: 'administrator_registration'

    end
    scope '/account' do
      get   '/reset-password'        => 'devise/passwords#new',    as: 'new_administrator_password'
      put   '/reset-password'        => 'devise/passwords#update', as: 'administrator_password'
      post  '/reset-password'        => 'devise/passwords#create'
      get   '/reset-password/change' => 'devise/passwords#edit',   as: 'edit_administrator_password'
      get   '/confirm'        => 'devise/confirmations#show',   as: 'administrator_confirmation'
      post  '/confirm'        => 'devise/confirmations#create'
      get   '/confirm/resend' => 'devise/confirmations#new',    as: 'new_administrator_confirmation'
      get '/cancel'   => 'devise/registrations#cancel', as: 'cancel_administrator_registration'
      get '/settings' => 'devise/registrations#edit',   as: 'edit_administrator_registration'
      put '/settings' => 'devise/registrations#update'
      delete '' => 'devise/registrations#destroy'
    end
  end

  get 'administrator/index', as: 'administrator_index'
  get 'administrator/home', as: 'administrator_home'

  get 'announcements/show_public_service'
  get 'announcements/show_question_answer'
  get 'announcements/show_contact'

  get 'announcements/show_procurement_entity_city_province'
  get 'announcements/show_procurement_entity_ministry'
  get 'announcements/show_procurement_entity_public_foundation'

  get 'announcements/show_bidder_list_registrative_form'
  get 'announcements/show_bidding_document'
  get 'announcements/show_planning_approval_correction'

  get 'announcements/show_gdpp_role'
  get 'announcements/show_gdpp_structure'

  get 'announcements/show_procurement_goods'

  resources :admin_announcements
  resources :announcements

  root 'announcements#index'

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  belongs_to :procurement_type

  has_attached_file :attachment, :url => "/:class/:attachment/:id/:basename.:extension", :path => ":rails_root/public/:class/:attachment/:id/:basename.:extension"
  has_attached_file :bidding_attachment, :url => "/:class/:attachment/:id/:basename.:extension", :path => ":rails_root/public/:class/:attachment/:id/:basename.:extension"
  validates_attachment :attachment, :bidding_attachment, :content_type => { :content_type => [
    "image/jpeg", "image/jpg", "image/gif", "image/png", 
    "application/pdf", "application/vnd.ms-excel", 
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", 
    "application/msword", 
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document"] },
     :size => { :in => 0..5.megabytes }
end

app/models/procurement_type.rb
class ProcurementType < ActiveRecord::Base
  has_many :announcements
end

app/controllers/admin_announcements_controller.rb
class AdminAnnouncementsController < ApplicationController
	 before_action :set_announcement, only: [:show, :edit, :delete, :destroy]

  layout "admin_application" 
  
  # we can use (layout "layout_name", except: [:method, :method])


  def index
    @admin_announcements = Announcement.all
  end

  def edit
    @admin_announcement = Announcement.find(params[:id])
  end

  def show
    
  end

  def new
    @admin_announcement = Announcement.new
  end

  def create
    @admin_announcement = Announcement.new(announcement_params)
    if @admin_announcement.save
      redirect_to admin_announcements_path
    else
      render 'new'
    end
  end

  def destroy
    @admin_announcement.destroy
    redirect_to admin_announcements_path
  end

  def update
    @admin_announcement = Announcement.find(params[:id])
    if @admin_announcement.update_attributes(announcement_params)
      redirect_to admin_announcements_path
    else
      render 'edit'
    end
  end

  def delete_attachment
    @admin_announcement = Announcement.find_by_id(params[:id])
    @admin_announcement.attachment = nil
    if @admin_announcement.save
      redirect_to admin_announcements_path
    else
      render 'new'
    end
  end

  def delete_bidding_attachment
    @admin_announcement = Announcement.find_by_id(params[:id])
    @admin_announcement.bidding_attachment = nil
    if @admin_announcement.save
      redirect_to admin_announcements_path
    else
      render 'new'
    end
  end
  
  private
  def set_announcement
    @admin_announcement = Announcement.find(params[:id])
  end

  def announcement_params
    # binding.pry
    params.require(:announcement).permit(:title, 
      :description, :entity, :bidding_expired_date, 
      :budget_source, :attachment, :bidding_attachment)
  end
end

app/controllers/administrator_controller.rb
class AdministratorController < ApplicationController
  before_action :authenticate_administrator!

  layout 'admin_application'

  def index
    @user = current_administrator
  end

  def home
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :delete, :destroy]

  # layout "admin_application" 
  
  # we can use (layout "layout_name", except: [:method, :method])

  def index
    # @announcements = Announcement.all
  end

  def show_public_service
    
  end

  def show_question_answer
    
  end

  def show_contact
    
  end

# Procurement entity

  def show_procurement_entity_city_province
    
  end
  
  def show_procurement_entity_ministry
    
  end

  def show_procurement_public_foundation
    
  end

# Download

  def show_bidder_list_registrative_form
    
  end

  def show_bidding_document
    
  end

  def show_planning_approval_correction
    
  end

# about
  def show_gdpp_role
    
  end
  def show_gdpp_structure
    
  end

# order menu
  def show_procurement_goods
    
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    administrator_index_path
  end

  # def after_sign_out_path_for(resource)
  #   administrator_home_path
  # end
end

app/helpers/admin_announcements_helper.rb
module AdminAnnouncementsHelper
end

app/helpers/administrator_helper.rb
module AdministratorHelper
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin_announcements/_form.html.erb
<%= simple_form_for(@admin_announcement, url: url ) do |f| %>
      <% if @admin_announcement.errors.any? %>
        <div id="error_explanation">}
          <h2><%= pluralize(@admin_announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

          <ul>
          <% @admin_announcement.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

<div class="row" >
  
    <div class="col-md-6" >
      <div class="row" >
        <div class="col-md-12" >
          <!-- column -->
          <%= f.input :title, label: 'Title' %>
        </div>
        <div class="col-md-12" >
          <!-- column -->
          <%= f.input :entity, label: 'Entity' %>
        </div>
      </div>
    </div>
    <div class="col-md-6" >
      <!-- col-6 -->
      <%= f.input :description, label: 'Description', :as => :text,  :input_html => {  :rows => 4, :style => 'height: 108px;' } %>
    </div>
  
</div>

<div class="row" >
  
    <div class="col-md-6" >
      <!-- column -->
       <%= f.input :bidding_expired_date, label: 'Bidding Expired Date', as: :date_picker %>
    </div>
    <div class="col-md-6" >
      <!-- column -->
      <%= f.input :budget_source, label: 'Budget Source' %>
    </div>
  
</div>

<div class="row" >
  
    <div class="col-md-6" >
      <!-- column -->
      <%= f.input :attachment, label: 'Attachment File', as: :file %>
    </div>
    <div class="col-md-6" >
      <!-- column -->
      <%= f.input :bidding_attachment, label: 'Bidding Attachment File', as: :file %>
    </div>
  
</div>


      <%= f.button :submit, label: 'Create Announcement', class: 'btn btn-primary background-color-fore' %>
    <% end %>

app/views/admin_announcements/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">កែប្រែសេចក្តីប្រកាស់</div>
  <div class="panel-body">
		<%= render 'form', { url: admin_announcement_path(@admin_announcement) } %>
		<hr>
		<%= link_to 'Show', admin_announcement_path %>
		<%= link_to 'Back', admin_announcements_path%>
	</div>
</div>

app/views/admin_announcements/index.html.erb
<div class="panel panel-default" >
  <div class="panel-heading" >
    គ្រប់គ្រងសេចក្តីប្រកាស់
  </div>
  <div class="panel-body" >
  
        <div class="table-responsive">
          <table  class="table table-bordered table-striped" >
            <thead>
              <tr>
                <th>Title</th>
                <th>Description</th>
                <!-- <th>Entity</th>
                <th>Exp Date</th>
                <th>Budget Source</th> -->
                <th>Attachment</th>
                <th>Bidding Attachment</th>
                <th>Action  </th>
                <!-- <th colspan="3"></th> -->
              </tr>
            </thead>

            <tbody>
              <% @admin_announcements.each do |announcement| %>
                <tr>
                  <td><%= announcement.title %></td>
                  <td><%= announcement.description %></td>
                 <!--  <td><%= announcement.entity %></td>
                  <td><%= announcement.bidding_expired_date %></td>
                  <td><%= announcement.budget_source %></td> -->
                  <td>
                    <% if announcement.attachment? %>
                      <%= link_to announcement.attachment_file_name, announcement.attachment.url, target: '_blank' %>
                    <% else %>
                      No attached file(s)
                    <% end %>
                  </td>
                   <td>
                   <% if announcement.attachment? %>
                     <%= link_to announcement.bidding_attachment_file_name, announcement.bidding_attachment.url, target: '_blank' %>
                    <% else %>
                      No attached file(s)
                    <% end %>
                   </td>
                  <td >
                  <div style="width: 50px ;">
                    <%= link_to '', admin_announcement_path(announcement), class: 'fa fa-folder-open', title: 'Show' %>
                    <%= link_to '', edit_admin_announcement_path(announcement), class: 'fa fa-edit', title: 'Edit'  %>
                    <%= link_to '', admin_announcement_path(announcement), method: :delete, data: { confirm: 'Are you sure?' } , class: 'fa  fa-remove color-danger ', title: 'Delete' %>
                  </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <br>

        <%= link_to 'បន្ថែមសេចក្តីប្រកាស់ថ្មី', new_admin_announcement_path , class: 'btn btn-primary background-color-fore' %>
  </div>

</div>

app/views/admin_announcements/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">បន្ថែមសេចក្តីប្រកាស់ថ្មី</div>
  <div class="panel-body">
  
  <%= render 'form', { url: admin_announcements_path }  %>

<hr>
	<%= link_to 'Back', admin_announcements_path  %>	


  </div>
</div>

app/views/admin_announcements/show.html.erb
<h1>Announcements#show</h1>
<p>Find me in app/views/announcements/show.html.erb</p>

<label>Title</label><%= @admin_announcement.title %><br/>
<label>Description</label><%= @admin_announcement.description %><br/>
<label>Entity</label><%= @admin_announcement.entity %><br/>
<label>Bidding Expired Date</label><%= @admin_announcement.bidding_expired_date %><br/>
<label>Budget Source</label><%= @admin_announcement.budget_source %><br/>
<label>Attachment</label><%= @admin_announcement.attachment_file_name %><br/>
<label>Bidding Attachment</label><%= @admin_announcement.bidding_attachment_file_name %><br/>

<%= link_to "Edit", edit_admin_announcement_path(@admin_announcement) %>
<%= link_to "Back", admin_announcements_path %>

app/views/administrator/home.html.erb
<h1>Administrator#home</h1>
<p>Find me in app/views/administrator/home.html.erb</p>

app/views/administrator/index.html.erb
<% if administrator_signed_in? %>
  <%= link_to 'log out', destroy_administrator_session_path, :method => :delete%>
  <div>Signed in as... <%= current_administrator.email %></div>
  <p><%= @user.username.capitalize %></p>
  <p><%= @user.email %></p>
<% end %>
<h1>Administrator#index</h1>
<p>Find me in app/views/administrator/index.html.erb</p>

app/views/announcements/_navigator.html.erb
    <nav class="navbar navbar-default background-color-fore ">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="only"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class=" navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li >
              <%= link_to 'ទំព័រដើម', root_path  %>
            </li>
            <li class="dropdown">
              <%= link_to '', class: 'dropdown-toggle', 'data-toggle': 'dropdown', role: 'button', 'aria-haspopup': 'true', 'aria-expanded': 'false'   do %>
                ស្ថាប័នអនុវត្តលទ្ធកម្ម
                <span class="caret"></span>
              <% end %>

              <ul class="dropdown-menu">
                <li><%= link_to 'ក្រសួង – ស្ថាប័នថ្នាក់កណ្តាល', announcements_show_procurement_entity_ministry_path %>
                </li>
                <li><%= link_to 'គ្រឹះស្ថានសាធារណៈ – សហគ្រាសសាធារណៈ', announcements_show_procurement_entity_public_foundation_path  %>
                </li>
                <li><%= link_to 'រាជធានី​ – ខេត្ត', announcements_show_procurement_entity_city_province_path %>
                </li>
              </ul>
            </li>
            
            <li >
              <%= link_to announcements_show_public_service_path do %>
                សេវាសាធារណៈ
                <span class="sr-only">(current)</span>
              <% end %>
            </li>

            <li class="dropdown">
              <%= link_to '', class: 'dropdown-toggle', 'data-toggle': 'dropdown', role: 'button', 'aria-haspopup': 'true', 'aria-expanded': 'false'   do %>
                អំពីស្ថាប័ន
                <span class="caret"></span>
              <% end %>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'តួនាទីអគ្គនាយកដ្ឋានលទ្ធកម្មសាធារណៈ', announcements_show_gdpp_role_path %>
                </li>
                <li>
                  <%= link_to 'រចនាសម្ព័ន្ធស្ថាប័ន', announcements_show_gdpp_structure_path %>
                </li>
                
              </ul>
            </li>

            <li>
              <!-- <a href="">ទំនាក់ទំនង</a> -->
              <%= link_to "ទំនាក់ទំនង", announcements_show_contact_path %>
            </li>
            <li >
              
              <%= link_to "សំណួរចម្លើយ", announcements_show_question_answer_path %>
            </li>
          </ul>
          
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

app/views/announcements/_right_sitebar.html.erb
<div class=" right-sitebar has-padding col-md-4 color-fore" >
    <% if  !request.fullpath.end_with?("/","/announcements") %>
        <div class=" widget-box has-shadow color-black ">
            <h2>សេចក្ដីជូនដំណឹងស្តីពីការដេញថ្លៃថ្មីៗ</h2>
                
                <div class="list-item-box" >
                    <p class="title" >សេចក្តីប្រកាស់ទី១ </p>
                    <p class="after-title" >សំណង់ 01-07-2015</p>
                </div>
                <div class="list-item-box" >
                    <p class="title" >សេចក្តីប្រកាស់ទី១ </p>
                    <p class="after-title" >សំណង់ 01-07-2015</p>
                </div>
                <div class="list-item-box" >
                    <p class="title" >សេចក្តីប្រកាស់ទី១ </p>
                    <p class="after-title" >សំណង់ 01-07-2015</p>
                </div>
                <div class="list-item-box" >
                    <p class="title" >សេចក្តីប្រកាស់ទី១ </p>
                    <p class="after-title" >សំណង់ 01-07-2015</p>
                </div>
        </div>
        
    <% end %>
    <div class=" widget-box has-shadow">
        <h2>ដំណឹងស្តីពីការដេញថ្លៃ</h2>
        <ul style="list-style:none">
            <li><%= link_to 'លទ្ធកម្មទំនេញ',    announcements_show_procurement_goods_path %></li>
            <li><%= link_to 'លទ្ធកម្មសំណង់',    announcements_show_procurement_goods_path %></li>
            <li><%= link_to 'លទ្ធកម្មសេវាកម្ម',    announcements_show_procurement_goods_path %></li>
            <li><%= link_to 'លទ្ធកម្មទីព្រឹក្សា',    announcements_show_procurement_goods_path %></li>
        </ul>
    </div>

    <div class=" widget-box has-shadow">
      <h2>ផែនការលទ្ធកម្ម</h2>
      
      <ul style="list-style:none" >
        <li> <%= link_to "ផែនការលទ្ធកម្មដើមឆ្នាំ ", '#' %></li>
        <li> <%= link_to "ផែនការលទ្ធកម្មកែតម្រូវ", '#' %></li>
      </ul> 

    </div>
    <% if  !request.fullpath.end_with?("/","/announcements") %>
    <div class="widget-box has-shadow">
      <h2>ច្បាប់និងលិខិតកត្តិយុទ្ធ</h2>
      
      <ul style="list-style:none" >
        <li> <%= link_to "ច្បាប់ ", '#' %></li>
        <li> <%= link_to "ព្រះរាជក្រិត្រ", '#' %></li>
        <li> <%= link_to "ប្រកាស់", '#' %></li>
        <li> <%= link_to "ឯកសាផ្សេងៗ", '#' %></li>
      </ul> 
        
    </div>
    <% end %>
    <div class="widget-box has-shadow">
      <h2> <%= "ការប្រគល់កិច្ចសន្យា" %> </h2>
      <ul style="list-style:none" >
        <li> <%= link_to "ដេញថ្លៃដោយប្រកួតប្រជែងជាអន្តរជាតិ", '#' %> </li>
        <li> <%= link_to "ពិគ្រោះថ្លៃ", '#' %></li>
        <li> <%= link_to "ស្ទង់តម្លៃ", '#' %></li>
      </ul>  
    </div>

</div>

app/views/announcements/show_bidder_list_registrative_form.html.erb
show_bidder_list_registrative_form.html.erb

app/views/announcements/show_bidding_document.html.erb
show_bidding_document.html.erb

app/views/announcements/show_contact.html.erb
<div>
  <h1 class="content-main-title" ><%= "អាសយដ្ឋានទំនាក់ទំនង" %></h1>

  <p class="title" ><b> <%= "អគ្គនាយកដ្ឋានលទ្ធកម្មសាធារណៈនៃក្រសួងសេដ្ឋកិច្ច និង ហិរញ្ញវត្ថុ" %> </b> </p>
  <p><%= "ផ្លូវលេខ ៩២ សង្កាត់វត្តភ្នំ ខ័ណដូនពេញ រាជធានីភ្នំពេញ" %></p>

</div>

<div id="map" style="height: 400px" ></div>

app/views/announcements/show_gdpp_role.html.erb
<h1><%= "ពំទាន់មានឯកសារ" %></h1>

app/views/announcements/show_gdpp_structure.html.erb
<br>
<p class="text-center" style="font-size: 25px; font-family:'khmer muol'; " >
  <%= 'អង្គការលេខរបស់អគនាយកដ្ឋានលទ្ធកម្មសាធារណៈ' %>
</p>
<hr>

<%= image_tag('hierarchy-photo.png' , style: 'width: 100%', align: 'center' ) %>

app/views/application/_navigator.html.erb
    <nav class="navbar navbar-default background-color-fore ">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="only"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class=" navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li >
              <%= link_to 'ទំព័រដើម', root_path  %>
            </li>
            <li class="dropdown">
              <%= link_to '', class: 'dropdown-toggle', 'data-toggle': 'dropdown', role: 'button', 'aria-haspopup': 'true', 'aria-expanded': 'false'   do %>
                ស្ថាប័នអនុវត្តលទ្ធកម្ម
                <span class="caret"></span>
              <% end %>

              <ul class="dropdown-menu">
                <li><%= link_to 'ក្រសួង – ស្ថាប័នថ្នាក់កណ្តាល', announcements_show_procurement_entity_ministry_path %>
                </li>
                <li><%= link_to 'គ្រឹះស្ថានសាធារណៈ – សហគ្រាសសាធារណៈ', announcements_show_procurement_entity_public_foundation_path  %>
                </li>
                <li><%= link_to 'រាជធានី​ – ខេត្ត', announcements_show_procurement_entity_city_province_path %>
                </li>
              </ul>
            </li>

            <li class="dropdown">
              <%= link_to '', class: 'dropdown-toggle', 'data-toggle': 'dropdown', role: 'button', 'aria-haspopup': 'true', 'aria-expanded': 'false'   do %>
                ទាញយកឯកសា
                <span class="caret"></span>
              <% end %>

              <ul class="dropdown-menu">
                <li><%= link_to 'ឯកសាដេញថ្លៃ', announcements_show_bidder_list_registrative_form_path %>
                </li>
                <li><%= link_to 'ពាក្យសុំចុះបញ្ជីដេញថ្លៃ', announcements_show_bidding_document_path  %>
                </li>
                <li><%= link_to 'ពាក្យសុំអនុម័តផែនការ និងផែនការលទ្ធកម្មកែតម្រូវ', announcements_show_planning_approval_correction_path %>
                </li>
              </ul>
            </li>

            <li >
              <%= link_to announcements_show_public_service_path do %>
                សេវាសាធារណៈ
                <span class="sr-only">(current)</span>
              <% end %>
            </li>

            <li class="dropdown">
              <%= link_to '', class: 'dropdown-toggle', 'data-toggle': 'dropdown', role: 'button', 'aria-haspopup': 'true', 'aria-expanded': 'false'   do %>
                អំពីស្ថាប័ន
                <span class="caret"></span>
              <% end %>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'តួនាទីអគ្គនាយកដ្ឋានលទ្ធកម្មសាធារណៈ', announcements_show_gdpp_role_path %>
                </li>
                <li>
                  <%= link_to 'រចនាសម្ព័ន្ធស្ថាប័ន', announcements_show_gdpp_structure_path %>
                </li>
                
              </ul>
            </li>

            <li>
              <!-- <a href="">ទំនាក់ទំនង</a> -->
              <%= link_to "ទំនាក់ទំនង", announcements_show_contact_path %>
            </li>
            <li >
              
              <%= link_to "សំណួរចម្លើយ", announcements_show_question_answer_path %>
            </li>
          </ul>
          
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

app/views/application/_right_sitebar.html.erb
<div class=" right-sitebar has-padding col-md-4 color-fore" >
    <div class=" widget-box has-shadow color-black ">
        <h2>សេចក្ដីជូនដំណឹងស្តីពីការដេញថ្លៃថ្មីៗ</h2>
            
            <div class="list-item-box" >
                <p class="title" >សេចក្តីប្រកាស់ទី១ </p>
                <p class="after-title" >សំណង់ 01-07-2015</p>
            </div>
            <div class="list-item-box" >
                <p class="title" >សេចក្តីប្រកាស់ទី១ </p>
                <p class="after-title" >សំណង់ 01-07-2015</p>
            </div>
            <div class="list-item-box" >
                <p class="title" >សេចក្តីប្រកាស់ទី១ </p>
                <p class="after-title" >សំណង់ 01-07-2015</p>
            </div>
            <div class="list-item-box" >
                <p class="title" >សេចក្តីប្រកាស់ទី១ </p>
                <p class="after-title" >សំណង់ 01-07-2015</p>
            </div>

    </div>

    <div class=" widget-box has-shadow">
        <h2>ដំណឹងស្តីពីការដេញថ្លៃ</h2>
        <ul style="list-style:none">
            <li><%= link_to 'លទ្ធកម្មទំនេញ',    announcements_show_procurement_goods_path %></li>
            <li><%= link_to 'លទ្ធកម្មសំណង់',    announcements_show_procurement_goods_path %></li>
            <li><%= link_to 'លទ្ធកម្មសេវាកម្ម',    announcements_show_procurement_goods_path %></li>
            <li><%= link_to 'លទ្ធកម្មទីព្រឹក្សា',    announcements_show_procurement_goods_path %></li>
        </ul>
    </div>

    <div class=" widget-box has-shadow">
        <h2>ផែនការលទ្ធកម្ម</h2>
        <p> ផែនការលទ្ធកម្មដើមឆ្នាំ </p>
        <p> ផែនការលទ្ធកម្មកែតម្រូវ </p>
    </div>

    <div class="widget-box has-shadow">
        <h2>ច្បាប់និងលិខិតកត្តិយុទ្ធ</h2>
        <p> ច្បាប់ </p>
        <p> ព្រះរាជក្រិត្រ </p>
        <p> ប្រកាស់</p>
        <p> ឯកសាផ្សេងៗ </p>
        
    </div>

    <div class="widget-box has-shadow">
        <h2>ការប្រគល់ឯកសា</h2>
        <p> អ.ដ.ប</p>
        <p> អ.ដ.ប</p>
        <p> អ.ដ.ប</p>
        <p> អ.ដ.ប</p>

        
        
    </div>
</div>